# Install Nginx example
- name: Install & Start Nginx
  hosts: localhost
  become: yes
  tasks:
  - name: Install nginx & python
    ansible.builtin.package:
      name:
        - nginx
        - python3
      state: present
  - name: Start nginx
    ansible.builtin.systemd:
      name: nginx
      state: started
      enabled: yes
  