# Functions in Ansible
- name: Converting into Uppercase
  hosts: localhost
  connection: local
  vars: 
    Course: "devops"
  tasks:
    - name: Convert into Uppercase
      ansible.builtin.debug:
        msg: "{{ Course | upper }}"

- name: Converting into Lowercase
  hosts: localhost
  connection: local
  vars: 
    Course: "DEVOPS"
  tasks:
    - name: Convert into Lowercasecase
      ansible.builtin.debug:
        msg: "{{ Course | lower }}"

# Functions in Ansible
- name: Converting into Uppercase
  hosts: localhost
  connection: local
  vars: 
    Course: "devops"
  tasks:
    - name: Convert into Uppercase
      ansible.builtin.debug:
        msg: "{{ Course | upper }}"

- name: Copy the files
  hosts: localhost
  connection: local
  tasks:
    - name: Copy nginx config file
      ansible.builtin.copy:
        src: /home/ec2-user/nginx.conf
        dest: /etc/nginx/nginx.conf
        backup: yes